# Generated by Django 3.0.2 on 2020-12-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
